# Change baseURL to web url
baseURL: "https://jarpiano.github.io/"
languageCode: "en-us"
title: "Jared Baron Panares"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "Portfolio"
  favicon: "/images/logo-v2.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light"

  variants:
    #standard: "fas fa-user-tie"
    #summer: "fas fa-umbrella-beach"
    #winter: "fas fa-snowflake"
    #autumn: "fab fa-canadian-maple-leaf"
    #spring: "fas fa-leaf"


  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  menus:
  #  disableContact: true
  #  disableAbout: true
  #  disableExperience: true
  #  disableEducation: true
  #  disableProjects: true
  #  disableAchievements: true
  #  disableSkills: true
    
  
  #color:
   # primaryColor: ""
    # titleColor completely overrides both dark/light 
    # titleColor: "#ff8400"

  # color preference
  color:
    titleColor: "#003C7E"
  #  textColor: "#402218"
  #  secondaryTextColor: "#865439"
  #  backgroundColor: "#FEFAF6"
  #  secondaryBackgroundColor: "#C68B59"
    primaryColor: "#003C7E"
  #  secondaryColor: 
  #  darkmode:
  #    textColor:
  #    secondaryTextColor:
  #    backgroundColor:
  #    secondaryBackgroundColor:
  #    primaryColor:
  #    secondaryColor:

  # Hero
  hero:
    enable: true
    intro: "Hey,"
    title: "I'm Jared"
    subtitle: "CS Major @ UT Austin"
    content: |- 
      An undergraduate student with aspirations in the broad field of computer science. <br>An aficionado of programming, cybersecurity, and web development. <br>Looking for opportunities in network security and software.
    image: /images/avatarv3.png
    button:
      enable: true
      name: "Repository"
      url: "https://github.com/Jarpiano/Jarpiano.github.io"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Jarpiano
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jared-baron-panares-841046242/
        - icon: fab fa-instagram
          url: https://www.instagram.com/jarpiano/
      # customIcons:
        # - icon: [image path]
        #   url: [link]

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/summer-avatar-brown.png"
    content: |-
      I'm Jared, an undergraduate student attending the University of Texas at Austin. I dabble in 
      tech and specialize in cybersecurity. Away from the keyboard, you can find me reading mycology books, 
      listening to indie, or strumming a guitar.
    skills:
      enable: true
      title: "Here's some stuff I'm interested in:"
      items:
        - "Web Development"
        - "Information Security"
        - "Mushroom Science"
        - "Indie Rock and R&B"
        - "Acoustic Guitar"

  # Experience
  experience:
    enable: true
    length: 2
    items:
      - exptitle: "SEC504: Hacker Tools, Techniques, and Incident Handling"
        date: "February 2024 - May 2024"
        content: |-
          I've completed the SEC504 course to prepare for the GCIH certification exam. 
          This course focuses on incident response through understanding attacker techniques, 
          highlighting the reaction process, and utilizing next-generation systems.

          *Provided by National Cyber Scholarship Foundation*

      - exptitle: "SEC401: Security Essentials - Network, Endpoint, and Cloud"
        date: "June 2023 - July 2023"
        content: |-
          I've completed SEC401, offered by SANS, in pursuit of the GSEC certification. 
          This course covers a broad number of topics within the industry including, but not limited 
          to, cloud fundamentals, Windows security, defendible network, etc.

          *Provided by National Cyber Scholarship Foundation*

      - exptitle: "SANS Foundations: Computers, Technology and Security"
        date: "June 2021 - September 2021"
        featuredLink:
          enable: true
          name: "View badge"
          url: "https://api.badgr.io/public/assertions/2bO1c9a6Rm2cQdbMHTdIxw"
        content: |-
          I have taken the SANS Foundations course offered by SANS Institute which helped me learn 
          the core aspects of cybersecurity such as offensive/defensive security, forensics, programming, 
          and more.

          *Provided by National Cyber Scholarship Foundation*

      - exptitle: "Freecodecamp (FCC)"
        date: "June 22 - Present"
        featuredLink:
          enable: true
          name: "View profile"
          url: "https://www.freecodecamp.org/Kyobito"
        content: |-
          I have earned the certificate for **Scientific Computing with Python**. I've done about 300
           hours of coursework (according to FCC) and have completed 5 projects involving Python along the way. 
           At the moment, I'm working towards their Front-end development course.


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "GIAC Certified Incident Handler (GCIH)"
        school: 
          name: "Issued by GIAC"
          url: "https://www.giac.org/"
        date: "2024"
        score: ""
        valid: "2024 - 2028"
        GPA: "" #None
        content: |-
          The GCIH exam highlights offensive operations security by focusing on utilizing and mitigating attacker tools/techniques.

          This exam includes, but isn't limited to:
            - Memory and Malware Investigation
            - Reconnaissance and Open-Source Intelligence
            - Incident Response
            - Endpoint Attack and Pivoting
            - Detecting Exploitation Tools and Evasive Techniques
        featuredLink:
          enable: true
          name: "See my badge"
          url: "https://www.credly.com/badges/bf867170-73ab-4b54-9d1f-31f46585bdde/public_url"
      - title: "GIAC Security Essentials (GSEC)"
        school: 
          name: "Issued by GIAC"
          url: "https://www.giac.org/"
        date: "2023"
        score: ""
        valid: "2023 - 2027"
        GPA: "" #None
        content: |-
          Shortly after taking the SEC401 course from SANS Institute, I passed my GSEC exam to obtain a certification! 

          This exam covered a broad range of topics including, but not limited to: 
           - Network and Cloud Security
           - Defense-In-Depth
           - Cryptographic Systems
           - Vulnerability Management
           - Windows Architecture
           - Linux and MacOS Security

           *Provided by National Cyber Scholarship Foundation*
        featuredLink:
          enable: true
          name: "See my badge"
          url: "https://www.credly.com/badges/4c00b960-4ad9-4f6c-aaa8-825685c72db3/public_url"
      - title: "GIAC Foundational Cybersecurity Technologies (GFACT)"
        school:
          name: "Issued by GIAC"
          url: "https://www.giac.org/"
        date: "2021"
        score: ""
        valid: "2021 - 2025"
        GPA: "" #None
        content: |-
          After taking the SANS Foundations course, I took the GFACT exam and was able to earn my 
          GFACT certification which is issued by GIAC Certifications, a well known organization in cybersecurity. 

          This exam covered core cybersecurity fundamentals including topics such as:
          - Computing Systems
          - Network Architecture 
          - Introduction to Servers and Services
          - Python and C Programming (as applies to IT)
          - Various Cybersecurity Methodology

          *Provided by National Cyber Scholarship Foundation*
        featuredLink:
          enable: true
          name: "See my badge"
          url: "https://www.credly.com/badges/0a307a0c-c351-49ab-ad47-326b83229095/public_url"
      - title: "Bachelors of Science"
        school:
          name: "University of Texas at Austin"
          url: "https://www.utexas.edu/"
        date: "2024 - 2028"
        content: |- 
          Seeking a Bachelors of Science in Computer Science and planning a concentration in cybersecurity.

          Relevant Coursework:
           - C S 429 Computer Organization and Architecture ^
           - C S 309 Autonomous Intelligent Robotics ^
           - C S 314 Data Structures
           - C S 311 Discrete Math for Computer Science

          Clubs:
           - Information & Systems Security Society (Fall '24 Cyber Scholar)
           - Texas Association for Computing Machinery

          <em style = "font-size: 90%">^ Current Classes</em>
      - title: "High School"
        school:
          name: "William B. Travis High School"
          url: "https://www.fortbendisd.com/ths"
        date: "2020 - 2024"
        score: ""
        GPA: "4.0 of 4.0" 
        content: |-
          Graduated from Travis high school. I've taken Pre-AP Computer Science I, AP Computer Science 
          Principles, AP Computer Science A, and Computer Science III.
          
          Clubs:
            - National Beta Club
            - Computer Science National Honor Society ('24 Officer)
            - Habitat for Humanity Travis Chapter ('23 Officer)
            - Academic Decathlon
            - National Honor Society
            - Science Olympiad

  # Achievements
  achievements:
    enable: true
    items:
      - title: GIAC Advisory Board
        content: Invitation only, email-based forum where IT Security professionals can exchange ideas and advice. Earned through an excellent score on a GIAC certification.
        url: https://www.credly.com/badges/33250358-1ea8-4650-8a95-93f24de04162/public_url
      - title: National Cyber Scholarship Scholar with Honors
        content: Solved hands-on challenges in CyberStart and were ranked in the top 1% of eligible players in the United States of America.
        links:
          - year: "2024"
            href: https://api.badgr.io/public/assertions/H1-yxF_HRGGuhxqOmbq1YA
          - year: "2023"
            href: https://api.badgr.io/public/assertions/-t0yxooXRribOcXAIC_fGA
      - title: National Cyber Scholarship Finalist
        content: Met Finalist requirements for respective years and gained access to the Cyber Foundations Academy.
        links:
          - year: "2022"
            href: https://api.badgr.io/public/assertions/j4y1h3zlSsi-HDLFJcfqDQ
          - year: "2021"
            href: https://api.badgr.io/public/assertions/twoc2ogWQiawYWcMWnRCUg
      - title: Cyberstart America Gold Award
        content: Gained at least 100,000 points in CyberStart through the CyberStart America program.
        links:
          - year: "2024"
            href: https://api.badgr.io/public/assertions/MNxfXVzTR5GLQE1lL1bZNQ
          - year: "2023"
            href: https://api.badgr.io/public/assertions/176AfSMPRwCP8fHVzkojSQ
          - year: "2022"
            href: https://api.badgr.io/public/assertions/mGy9frpqR8KivcS4k1d0gw
          - year: "2021"
            href: https://api.badgr.io/public/assertions/Ynm53ymtS_OBQM3Z4KwLfg

  # all images must have an aspect ratio of 1:1, mostly colored, and look alright when expanded
  # Projects
  projects:
    enable: true
    items:
      - title: Website Collection
        content: |-
          My personal front-end portfolio composed of projects spanning years.
        image: /images/project-logo.png
        featured:
          name: See websites
          link: '/blog/websites'
        badges:
          - "Hugo"
          - "HTML"
          - "Svelte"
          - "Front-End"
      - title: Freecodecamp Library
        content: |-
         An assortment of my activities on Freecodecamp along with certifications
        image: /images/fcc-project-logo.jpg
        featured:
          name: See Profile
          link: https://www.freecodecamp.org/Kyobito
        badges:
          - "Python"
      - title: Community Discord Bot
        content: |-
          A bot built and personalized for my Discord community. It utilizes discord.py and is able to access the Hypixel and Imgur APIs.
        image: /images/pencil-bot-V2.png
        featured:
          name: See Repository
          link: https://github.com/Kyobito/Pencils-Latest
        badges:
          - "Bot"
          - "Python"  
      - title: CyberStart America
        content: |-
          Participated in a cybersecurity competition and named NCSF Scholar with Honors.
        image: /images/ncsf-honors-banner.jpg
        featured:
          name: See Page
          link: http://jarpiano.github.io/blueprint/ncsf/
        badges:
          - Cybersecurity
      - title: Blog
        content: |-
          Articles recollecting my thoughts on tech and software.
        image: /images/blog-image.jpg
        featured:
          name: See Blog
          link: /blog
        

  #Contact
  contact:
    enable: true
    content: You can reach me via email! My inbox is always open for academic and professional inquiries.
    email: barcousticjp@gmail.com
    btnName: Contact me

  skills:
    enable: true

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/Jarpiano
      linkedin: https://www.linkedin.com/in/jared-baron-panares-841046242/
      twitter: https://twitter.com/RealJarpiano
      instagram: https://www.instagram.com/jarpiano/
