# Change baseURL to web url
baseURL: "http://jarpiano.github.io/"
languageCode: "en-us"
title: "Jarpiano | Jared Baron Panares"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "Portfolio"
  favicon: "/images/logo-v2.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light"

  variants:
    standard: "fas fa-user-tie"
    summer: "fas fa-umbrella-beach"
    #winter: "fas fa-snowflake"
    #autumn: "fab fa-canadian-maple-leaf"
    #spring: "fas fa-leaf"


  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  menus:
    disableContact: true
  #  disableAbout: true
  #  disableExperience: true
  #  disableEducation: true
  #  disableProjects: true
  #  disableAchievements: true
    
  
  color:
    primaryColor: ""
    # titleColor completely overrides both dark/light 
    # titleColor: "#ff8400"

  # Hero
  hero:
    enable: true
    intro: "Hello, I'm"
    title: "Jared Baron"
    subtitle: "A Caffeinated Coder"
    content: "A high school student aspiring to major in computer science. I dabble in programming, cybersecurity, and I'm on my way to learn machine learning."
    image: /images/me-icon.jpg
    button:
      enable: false
      name: "Resume"
      url: "#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Kyobito
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jared-baron-panares-841046242/
      customIcons:
        - icon: /fav.png
          url: "https://gohugo.io/"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/chipmunk-square.jpg" #"/images/summer-avatar.jpg"
    content: |-
      I'm Jared Baron Panares, a current high school student at William B. Travis High School. I frequently code in my spare time and seek to always improve. When I'm not at my desk, you can find me traveling, playing guitar, and enjoying a nice cup of joe.
    skills:
      enable: true
      title: "Here's some stuff I'm interested in:"
      items:
        - "Python"
        - "Java"
        - "Machine Learning"
        - "Cybersecurity"
        - "Web development"

  # Experience
  experience:
    enable: true
    length: 2
    items:
      - exptitle: "SANS Foundations: Computers, Technology and Security"
        date: "June 2021 - September 2021"
        featuredLink:
          enable: true
          name: "View badge"
          url: "https://api.badgr.io/public/assertions/2bO1c9a6Rm2cQdbMHTdIxw"
        content: I have taken the SANS Foundations course offered by SANS Institute which helped me learn the core aspects of cybersecurity such as offensive/defensive security, forensics, programming, and more.

      - exptitle: "Freecodecamp (FCC)"
        date: "June 22 - Current day"
        featuredLink:
          enable: true
          name: "View profile"
          url: "https://www.freecodecamp.org/Kyobito"
        content: |
          I have earned the certificate for **Scientific Computing with Python**. I've done about 300 hours of coursework (accourding to FCC) and have completed 5 projects involving Python along the way. At the moment, I'm working towards their Front-end development course.


  # Education
  # Omit all scores and GPAs
  education:
    enable: true
    # index: true
    items:
      - title: "GIAC Foundational Cybersecurity Technologies (GFACT)"
        school:
          name: "Issued by GIAC"
          url: "https://www.giac.org/"
        date: "2021"
        score: ""
        valid: "2021 - 2025"
        GPA: "" #None
        content: |-
          After taking the SANS Foundations course, I took the GFACT exam and was able to earn my GFACT certification which is issued by GIAC Certifications, a well known organization in cybersecurity.
        featuredLink:
          enable: true
          name: "See my badge"
          url: "https://www.credly.com/badges/0a307a0c-c351-49ab-ad47-326b83229095/public_url"
      - title: "High School"
        school:
          name: "William B. Travis high school"
          url: "https://www.fortbendisd.com/ths"
        date: "2020 - Current day"
        score: "" #None
        GPA: "" #Not yet
        content: |-
          An incoming junior at Travis high school. I've taken Pre-AP Computer Science and AP Computer Science Principles, and I'll soon be taking AP Computer Science A.
          
          Clubs:
            - National Beta Club
            - National Computer Science Honor Society
            - Habitat for Humanity

  # Achievements
  achievements:
    enable: true
    items:
      - title: National Cyber Scholarship Finalist 2022
        content: Issued by the National Cyber Scholarship Foundation
        url: https://api.badgr.io/public/assertions/j4y1h3zlSsi-HDLFJcfqDQ
      - title: Cyberstart America Gold Award 2021 - 2022
        content: Issued by Cyberstart America
        url: https://api.badgr.io/public/assertions/mGy9frpqR8KivcS4k1d0gw
      - title: National Cyber Scholarship Finalist 2021
        content: Issued by the National Cyber Scholarship Foundation
        url: https://api.badgr.io/public/assertions/twoc2ogWQiawYWcMWnRCUg
      - title: Cyberstart America Gold Award 2020 - 2021
        content:  Issued by Cyberstart America
        url: https://api.badgr.io/public/assertions/Ynm53ymtS_OBQM3Z4KwLfg

  # all images must have an aspect ratio of 1:1, mostly colored, and look alright when expanded
  # projects
  projects:
    enable: true
    items:
      - title: JP Website
        content: |-
          My personal portfolio site. It was made using the Hugo framework with gurusabarish's Hugo Profile theme.
        image: /images/project-logo.png
        featured:
          name: See Repository
          link: https://github.com/Jarpiano/Jarpiano.github.io
        badges:
          - "Hugo"
          - "Bootstrap"
          - "HTML"
      - title: Freecodecamp Library
        content: |-
         An assortment of my activities on Freecodecamp which includes certifications.
         images  
        image: /images/fcc-project-logo.jpg
        featured:
          name: See Profile
          link: https://www.freecodecamp.org/Kyobito
        badges:
          - "Python"
      - title: Habitat Pilot
        content: |-
         A website for my volunteering club. A current work in progress.
        image: /images/habitat-logo.png
        featured:
          name: See Website
          link: https://jarpiano.github.io/habitat-pilot/
        badges:
          - "Hugo"
          - "Bootstrap"
          - "HTML"
        


  #Contact
  contact:
    enable: false
    content: You can reach me via email! My inbox is always open for any opportunities regarding computer science and anything similar.
    email: example@gmail.com
    btnName: Contact me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/Jarpiano
      linkedin: https://www.linkedin.com/in/jared-baron-panares-841046242/
      twitter: https://twitter.com/RealJarpiano
