# Change baseURL to web url
baseURL: "https://jarpiano.github.io/"
languageCode: "en-us"
title: "Jared Baron Panares | Jarpiano"
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "Portfolio"
  favicon: "/images/logo-v2.png"

  theme:
    disableThemeToggle: false
    defaultTheme: "light"

  variants:
    standard: "fas fa-user-tie"
    summer: "fas fa-umbrella-beach"
    winter: "fas fa-snowflake"
    #autumn: "fab fa-canadian-maple-leaf"
    #spring: "fas fa-leaf"


  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  menus:
    disableContact: true
  #  disableAbout: true
  #  disableExperience: true
  #  disableEducation: true
  #  disableProjects: true
  #  disableAchievements: true
  #  disableSkills: true
    
  
  color:
    primaryColor: ""
    # titleColor completely overrides both dark/light 
    # titleColor: "#ff8400"

  # Hero
  hero:
    enable: true
    intro: "Hello, I'm"
    title: "Jared Baron"
    subtitle: "The Caffeinated Coder"
    content: |- 
      A high school student, curious by nature, with aspirations in computer science. An aficionado of programming, cybersecurity, and web development. Working towards another GIAC certification.
    image: /images/me-icon.jpg
    button:
      enable: true
      name: "Repository"
      url: "https://github.com/Jarpiano/Jarpiano.github.io"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Jarpiano
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jared-baron-panares-841046242/
        - icon: fab fa-instagram
          url: https://www.instagram.com/jarpiano/
      # customIcons:
        # - icon: [image path]
        #   url: [link]

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/summer-avatar.jpg"
    content: |-
      I'm Jared, a high school student stationed at William B. Travis High School. I'm well-versed in tech topics but always in pursuit of improvement. When I'm not typing away, you can find me reading a book, listening to music, or under the sun.
    skills:
      enable: true
      title: "Here's some stuff I'm interested in:"
      items:
        - "Python"
        - "Java"
        - "Machine Learning"
        - "Cybersecurity"
        - "Web development"

  # Experience
  experience:
    enable: true
    length: 2
    items:
      - exptitle: "SANS Foundations: Computers, Technology and Security"
        date: "June 2021 - September 2021"
        featuredLink:
          enable: true
          name: "View badge"
          url: "https://api.badgr.io/public/assertions/2bO1c9a6Rm2cQdbMHTdIxw"
        content: I have taken the SANS Foundations course offered by SANS Institute which helped me learn the core aspects of cybersecurity such as offensive/defensive security, forensics, programming, and more.

      - exptitle: "Freecodecamp (FCC)"
        date: "June 22 - Current day"
        featuredLink:
          enable: true
          name: "View profile"
          url: "https://www.freecodecamp.org/Kyobito"
        content: |
          I have earned the certificate for **Scientific Computing with Python**. I've done about 300 hours of coursework (according to FCC) and have completed 5 projects involving Python along the way. At the moment, I'm working towards their Front-end development course.


  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "GIAC Foundational Cybersecurity Technologies (GFACT)"
        school:
          name: "Issued by GIAC"
          url: "https://www.giac.org/"
        date: "2021"
        score: ""
        valid: "2021 - 2025"
        GPA: "" #None
        content: |-
          After taking the SANS Foundations course, I took the GFACT exam and was able to earn my GFACT certification which is issued by GIAC Certifications, a well known organization in cybersecurity.
        featuredLink:
          enable: true
          name: "See my badge"
          url: "https://www.credly.com/badges/0a307a0c-c351-49ab-ad47-326b83229095/public_url"
      - title: "High School"
        school:
          name: "William B. Travis High School"
          url: "https://www.fortbendisd.com/ths"
        date: "2020 - Current day"
        score: ""
        GPA: "" 
        content: |-
          A junior at Travis high school. I've taken Pre-AP Computer Science, AP Computer Science Principles, and currently taking AP Computer Science A.
          
          Clubs:
            - National Beta Club
            - Computer Science National Honor Society ('24 Officer)
            - Habitat for Humanity Travis Chapter ('23 Officer)
            - Academic Decathlon
            - National Honor Society

  # Achievements
  achievements:
    enable: true
    items:
      - title: National Cyber Scholarship Scholar with Honors 2023
        content: Issued by the National Cyber Scholarship Foundation
        utl: https://api.badgr.io/public/assertions/-t0yxooXRribOcXAIC_fGA
      - title: National Cyber Scholarship Finalist 2022
        content: Issued by the National Cyber Scholarship Foundation
        url: https://api.badgr.io/public/assertions/j4y1h3zlSsi-HDLFJcfqDQ
      - title: Cyberstart America Gold Award '21 - '22
        content: Issued by Cyberstart America
        url: https://api.badgr.io/public/assertions/mGy9frpqR8KivcS4k1d0gw
      - title: National Cyber Scholarship Finalist 2021
        content: Issued by the National Cyber Scholarship Foundation
        url: https://api.badgr.io/public/assertions/twoc2ogWQiawYWcMWnRCUg
      - title: Cyberstart America Gold Award '20 - '21
        content: Issued by Cyberstart America
        url: https://api.badgr.io/public/assertions/Ynm53ymtS_OBQM3Z4KwLfg
      - title: Cyberstart America Gold Award '22 - '23
        content: Issued by Cyberstart America
        url: https://api.badgr.io/public/assertions/176AfSMPRwCP8fHVzkojSQ

  # all images must have an aspect ratio of 1:1, mostly colored, and look alright when expanded
  # Projects
  projects:
    enable: true
    items:
      - title: JP Website
        content: |-
          My personal portfolio site - made using the Hugo framework with gurusabarish's Hugo Profile theme.
        image: /images/project-logo.png
        featured:
          name: See Repository
          link: https://github.com/Jarpiano/Jarpiano.github.io
        badges:
          - "Hugo"
          - "Bootstrap"
          - "HTML"
      - title: Freecodecamp Library
        content: |-
         An assortment of my activities on Freecodecamp along with certifications
        image: /images/fcc-project-logo.jpg
        featured:
          name: See Profile
          link: https://www.freecodecamp.org/Kyobito
        badges:
          - "Python"
      - title: Habitat For Humanity THS
        content: |-
         A website for the Habitat For Humanity Travis Chapter - made during my time as officer.
        image: /images/habitat-logo.png
        featured:
          name: See Website
          link: https://habitat-for-humanity-ths.github.io/
        badges:
          - "Hugo"
          - "Bootstrap"
          - "HTML"
      - title: Community Discord Bot
        content: |-
          A bot built and personalized for my Discord community. It utilizes discord.py and is able to access the Hypixel and Imgur APIs.
        image: /images/pencil-bot-V2.png
        featured:
          name: See Repository
          link: https://github.com/Kyobito/Pencils-Latest
        badges:
          - "Bot"
          - "Python"  
      - title: CyberStart America
        content: |-
          Participated in a cybersecurity competition and named NCSF Scholar with Honors.
        image: /images/ncsf-honors-banner.jpg
        featured:
          name: See Page
          link: http://jarpiano.github.io/blueprint/ncsf/

  #Contact
  contact:
    enable: false
    content: You can reach me via email! My inbox is always open for any opportunities regarding computer science and anything similar.
    email: example@gmail.com
    btnName: Contact me

  skills:
    enable: true

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/Jarpiano
      linkedin: https://www.linkedin.com/in/jared-baron-panares-841046242/
      twitter: https://twitter.com/RealJarpiano
      instagram: https://www.instagram.com/jarpiano/
